base:
  url: ${BASE_URL}

app:
  oauth2:
    success-redirect-url: ${SUCCESS_REDIRECT}
    failure-redirect-url: ${FAILURE_REDIRECT}
  mail:
    sender: ${MAIL_SET_FROM}
    to: ${MAIL_TO}

jwt:
  secret: ${JWT_SECRET}
  expirationMs: ${JWT_EXPIRATION_MS}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          yandex:
            client-id: ${YANDEX_CLIENT_ID}
            client-secret: ${YANDEX_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${YANDEX_REDIRECT_URI}
            scope:
              - "login:email"
              - "login:info"
            client-name: Yandex
            provider: yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: default_email

  output:
    ansi:
      enabled: always

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_AUTH}
          starttls:
            enable: ${SPRING_MAIL_STARTTLS_ENABLE}
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    oauth:
      client-id: ${YANDEX_CLIENT_ID}
      client-secret: ${YANDEX_CLIENT_SECRET}
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

logging:
  config: classpath:logback-spring.xml
