logging:
  pattern:
    dateformat: dd-MM-yyyy 'T' HH:mm:ss.SSS
  level:
    root: info
    com.greem4.springmedicines: info
    com.greem4.springmedicines.util.aspect: info
    com.zaxxer.hikari: info
    org.hibernate: info
    org.hibernate.orm.connections.pooling: OFF
  file:
    name: loggingFile.log
    path: ./logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medicines_db
    username: post
    password: post
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jpa:
    properties:
        hibernate:
          show_sql: true
          format_sql: true
          database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true