logging:
  pattern:
    dateformat: dd-MM-yyyy 'T' HH:mm:ss
  level:
    root: info
    com.greem4.springmedicines: info
    com.greem4.springmedicines.util.aspect: info
    com.zaxxer.hikari: info
    org.hibernate: info
    org.springframework.security: debug
    org.hibernate.orm.connections.pooling: OFF
  file:
    name: ./logs/loggingFile.log

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medicines_db
    username: post
    password: post
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    properties:
        hibernate:
          show_sql: true
          format_sql: true
          database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  output:
    ansi:
      enabled: always

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false

  mail:
    host: smtp.yandex.ru
    port: 465
    username: medicineSpringMail@yandex.ru
    password: Xj6-qZJ-dMz-Vmg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true